function State_Vector_Current = Function_Process_Heading_Position_Velocity(Velocity_Previous,...
                                                                           Psi_Heading_Previous,...
                                                                           Heading_Rate_Previous,...
                                                                           Bias_Previous,...
                                                                           Position_X_Previous,...
                                                                           Position_Y_Previous,...
                                                                           Time_Integration_Euler,...
                                                                           Time_Constant_Ship,...
                                                                           Rudder_Angle_Previous,...
                                                                           Ship_Static_Gain)

% This function models the non linear function that reprezents the
% kinematic of a surface moving ship on a 2D plane.

Velocity_Current = Velocity_Previous;
Psi_Heading_Current = Psi_Heading_Previous + Time_Integration_Euler*Heading_Rate_Previous;
Heading_Rate_Current = Heading_Rate_Previous*(1 - Time_Integration_Euler/Time_Constant_Ship) + ...
                       Time_Integration_Euler*(Ship_Static_Gain/Time_Constant_Ship)*Rudder_Angle_Previous + ...
                       Time_Integration_Euler*Bias_Previous;
Bias_Current = Bias_Previous;
Position_X_Current = Position_X_Previous + Velocity_Previous*Time_Integration_Euler*sin(Psi_Heading_Previous);
Position_Y_Current = Position_Y_Previous + Velocity_Previous*Time_Integration_Euler*cos(Psi_Heading_Previous);

State_Vector_Current = [Velocity_Current;
                        Psi_Heading_Current;
                        Heading_Rate_Current;
                        Bias_Current;
                        Position_X_Current;
                        Position_Y_Current];

end

