function State_Vector_Current = Function_Process_Model_2(Position_X_Previous,...
                                                         Position_Y_Previous,...
                                                         Psi_Heading_Previous,...
                                                         Heading_Rate_Previous,...
                                                         Bias_Previous,...
                                                         Velocity_Previous,...
                                                         Time_Integration_Euler,...
                                                         Time_Constant_Ship,...
                                                         Rudder_Angle_Previous,...
                                                         Ship_Static_Gain,...
                                                         Acceleration_Previous)

% This function models the non linear function that reprezents the
% kinematic of a surface moving ship on a 2D plane.

Position_X_Current = Position_X_Previous + Velocity_Previous*Time_Integration_Euler*sin(Psi_Heading_Previous);
Position_Y_Current = Position_Y_Previous + Velocity_Previous*Time_Integration_Euler*cos(Psi_Heading_Previous);
Psi_Heading_Current = Psi_Heading_Previous + Time_Integration_Euler*Heading_Rate_Previous;
Heading_Rate_Current = Heading_Rate_Previous*(1 - Time_Integration_Euler/Time_Constant_Ship) + ...
                       Time_Integration_Euler*(Ship_Static_Gain/Time_Constant_Ship)*Rudder_Angle_Previous + ...
                       Time_Integration_Euler*Bias_Previous;
Bias_Current = Bias_Previous;
Velocity_Current = Velocity_Previous + Time_Integration_Euler*Acceleration_Previous;
Acceleration_Current = Acceleration_Previous;
State_Vector_Current = [Position_X_Current;
                        Position_Y_Current;
                        Psi_Heading_Current;
                        Heading_Rate_Current;
                        Bias_Current;
                        Velocity_Current;
                        Acceleration_Current];

end

