function State_Vector_Current = Function_Process_Heading_Position_Velocity_Waves(Acceleration_Waves_Previous,...
                                                                                 Heading_Waves_Previous,...
                                                                                 Psi_Heading_Previous,...
                                                                                 Heading_Rate_Previous,...
                                                                                 Bias_Previous,...
                                                                                 Position_X_Previous,...
                                                                                 Position_Y_Previous,...
                                                                                 Velocity_Previous,...
                                                                                 Time_Integration_Euler,...
                                                                                 Time_Constant_Ship,...
                                                                                 Rudder_Angle_Previous,...
                                                                                 Ship_Static_Gain,...
                                                                                 Pulsation_Waves,...
                                                                                 Damping_Waves)

% This function models the non linear function that reprezents the
% kinematic of a surface moving ship on a 2D plane.
Acceleration_Waves_Current = Acceleration_Waves_Previous + Time_Integration_Euler*Heading_Waves_Previous;
Heading_Waves_Current = Heading_Waves_Previous + Time_Integration_Euler*(-Pulsation_Waves^2*Acceleration_Waves_Previous - ...
                        2*Damping_Waves*Pulsation_Waves*Heading_Waves_Previous);
Psi_Heading_Current = Psi_Heading_Previous + Time_Integration_Euler*Heading_Rate_Previous;
Heading_Rate_Current = Heading_Rate_Previous*(1 - Time_Integration_Euler/Time_Constant_Ship) + ...
                       Time_Integration_Euler*(Ship_Static_Gain/Time_Constant_Ship)*Rudder_Angle_Previous + ...
                       Time_Integration_Euler*Bias_Previous;
Bias_Current = Bias_Previous;
Position_X_Current = Position_X_Previous + Velocity_Previous*Time_Integration_Euler*sin(Psi_Heading_Previous);
Position_Y_Current = Position_Y_Previous + Velocity_Previous*Time_Integration_Euler*cos(Psi_Heading_Previous);
Velocity_Current = Velocity_Previous;

% Output creation:
State_Vector_Current = [Acceleration_Waves_Current;
                        Heading_Waves_Current;
                        Psi_Heading_Current;
                        Heading_Rate_Current;
                        Bias_Current;
                        Position_X_Current;
                        Position_Y_Current;
                        Velocity_Current];

end

