function STATE_VECTOR_CURRENT = FUNCTION_PROCESS_MODEL_HEADING_POSITION_AZIMUTH(EAST_POSITION_X_PREVIOUS,NORTH_POSITION_Y_PREVIOUS,...
                                                                                PSI_HEADING_PREVIOUS,VELOCITY_PREVIOUS,...
                                                                                TIME_STEP_HW)
% This function reprezents the first term of the first order Taylor
% Series expantion.

EAST_POSITION_X_CURRENT = EAST_POSITION_X_PREVIOUS + VELOCITY_PREVIOUS*TIME_STEP_HW*sin(PSI_HEADING_PREVIOUS);
NORTH_POSITION_Y_CURRENT = NORTH_POSITION_Y_PREVIOUS + VELOCITY_PREVIOUS*TIME_STEP_HW*cos(PSI_HEADING_PREVIOUS);
PSI_HEADING_CURRENT = PSI_HEADING_PREVIOUS;
VELOCITY_CURRENT = VELOCITY_PREVIOUS;
STATE_VECTOR_CURRENT = [EAST_POSITION_X_CURRENT;NORTH_POSITION_Y_CURRENT;PSI_HEADING_CURRENT;VELOCITY_CURRENT];

end

