function STATE_VECTOR_CURRENT = FUNCTION_PROCESS_MODEL(POSITION_X_PREVIOUS,POSITION_Y_PREVIOUS,...
                                                       PSI_HEADING_PREVIOUS,VELOCITY_PREVIOUS,...
                                                       TIME_STEP_HW)

% This function models the non linear function that reprezents the
% kinematic of a surface moving ship on a 2D plane.

POSITION_X_CURRENT = POSITION_X_PREVIOUS + VELOCITY_PREVIOUS*TIME_STEP_HW*cos(PSI_HEADING_PREVIOUS);
POSITION_Y_CURRENT = POSITION_Y_PREVIOUS + VELOCITY_PREVIOUS*TIME_STEP_HW*sin(PSI_HEADING_PREVIOUS);
PSI_HEADING_CURRENT = PSI_HEADING_PREVIOUS;
VELOCITY_CURRENT = VELOCITY_PREVIOUS;
STATE_VECTOR_CURRENT = [POSITION_X_CURRENT;POSITION_Y_CURRENT;PSI_HEADING_CURRENT;VELOCITY_CURRENT];

end

